# the path to the wav files used for merging and converting to h5
audio: "C:/Users/marc.andresen/Documents/Aufnahme1_neues_Array/Recorded/Motorradgeraeusch_untenRechts"
# the path to the video file
video: "C:/Users/marc.andresen/Documents/Aufnahme1_neues_Array/Recorded/Motorradgeraeusch_untenRechts/WIN_20220712_14_06_57_Pro_Trim.mp4"
# the fps of the beamforming map
fps: 10
# the band-center frequency of the sound you want to measure
frequency: 400
# distance between array and sound source
distance: 1.5
# resolution of the beamforming map
resolution: 0.5
# the dimensions of the RectGrid the size of the canvas
x_min: -3
x_max: 3
y_min: -2.1
y_max: 2.1
# path to the microphone xml file
array: "C:/Users/marc.andresen/Documents/GitHub/Beamforming-Algorithmus/Beamforming/Python_Beamforming/config/mic32.xml"
# output path
output: "."